version: '3'

services:
  payload:
    container_name: payload
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install --production && yarn build"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/innovadb
      PORT: 3000
      NODE_ENV: production
      PAYLOAD_SECRET: dc4d364eefdb590ede0212e0

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    ports:
      - 7700:7700

volumes:
  data:
  node_modules:
